"""Meter 数据访问层（repository）。

按业务域拆分为子模块，此处统一 re-export 对外符号，
保持 ``from app.modules.meter import repository as repo`` 后属性访问（``repo.xxx``）不变。
"""

from app.modules.meter.repository._utils import _coerce_date_fields, _parse_multi
from app.modules.meter.repository.date_stats import (
    get_gas_detector_date_stats,
    get_instrument_date_stats,
)
from app.modules.meter.repository.departments import (
    count_records_by_department,
    create_department,
    get_department_by_id,
    get_department_by_source_and_name,
    list_departments,
    rename_department_in_records,
    soft_delete_department,
    sync_departments,
    update_department,
)
from app.modules.meter.repository.due import (
    get_notifiable_departments,
    list_gas_detectors_due_for_calibration,
    list_gas_detectors_due_grouped,
    list_instruments_due_for_calibration,
    list_instruments_due_grouped,
)
from app.modules.meter.repository.gas_detectors import (
    batch_soft_delete_gas_detectors,
    count_reports_by_gas_detector_ids,
    create_gas_detector,
    exists_gas_detector_by_product_number,
    get_all_gas_detector_ids,
    get_gas_detector_by_id,
    get_gas_detector_departments,
    get_gas_detector_filter_options,
    get_max_gas_detector_sort_order,
    list_gas_detectors,
    soft_delete_gas_detector,
    update_gas_detector,
)
from app.modules.meter.repository.instruments import (
    batch_soft_delete_instruments,
    count_reports_by_instrument_ids,
    create_instrument,
    exists_instrument_by_asset_number,
    get_all_instrument_ids,
    get_instrument_by_id,
    get_instrument_departments,
    get_instrument_filter_options,
    get_max_instrument_sort_order,
    list_instruments,
    soft_delete_instrument,
    update_instrument,
)
from app.modules.meter.repository.overview import (
    get_gas_detector_overview,
    get_instrument_overview,
)
from app.modules.meter.repository.reports import (
    create_report,
    find_existing_certificate_nos,
    find_gas_detector_by_name_and_product,
    find_instrument_by_name_and_serial,
    get_report_by_id,
    list_reports_by_gas_detector,
    list_reports_by_instrument,
    search_gas_detectors_by_name,
    search_instruments_by_name,
    soft_delete_report,
    update_report_certificate_no,
    update_report_date,
)
from app.modules.meter.repository.settings import (
    get_or_create_meter_settings,
    update_meter_settings,
)

__all__ = [
    "_coerce_date_fields",
    "_parse_multi",
    "batch_soft_delete_gas_detectors",
    "batch_soft_delete_instruments",
    "count_records_by_department",
    "count_reports_by_gas_detector_ids",
    "count_reports_by_instrument_ids",
    "create_department",
    "create_gas_detector",
    "create_instrument",
    "create_report",
    "exists_gas_detector_by_product_number",
    "exists_instrument_by_asset_number",
    "find_existing_certificate_nos",
    "find_gas_detector_by_name_and_product",
    "find_instrument_by_name_and_serial",
    "get_all_gas_detector_ids",
    "get_all_instrument_ids",
    "get_department_by_id",
    "get_department_by_source_and_name",
    "get_gas_detector_by_id",
    "get_gas_detector_date_stats",
    "get_gas_detector_departments",
    "get_gas_detector_filter_options",
    "get_gas_detector_overview",
    "get_instrument_by_id",
    "get_instrument_date_stats",
    "get_instrument_departments",
    "get_instrument_filter_options",
    "get_instrument_overview",
    "get_max_gas_detector_sort_order",
    "get_max_instrument_sort_order",
    "get_notifiable_departments",
    "get_or_create_meter_settings",
    "get_report_by_id",
    "list_departments",
    "list_gas_detectors",
    "list_gas_detectors_due_for_calibration",
    "list_gas_detectors_due_grouped",
    "list_instruments",
    "list_instruments_due_for_calibration",
    "list_instruments_due_grouped",
    "list_reports_by_gas_detector",
    "list_reports_by_instrument",
    "rename_department_in_records",
    "search_gas_detectors_by_name",
    "search_instruments_by_name",
    "soft_delete_department",
    "soft_delete_gas_detector",
    "soft_delete_instrument",
    "soft_delete_report",
    "sync_departments",
    "update_department",
    "update_gas_detector",
    "update_instrument",
    "update_meter_settings",
    "update_report_certificate_no",
    "update_report_date",
]
