"""生产模块 API 契约。按聚合拆分：product / route / batch / execution / trace / intermediate。"""

from app.modules.production.schemas.batch import (
    BatchCreate,
    BatchDetailOut,
    BatchOut,
    ChildBatchIn,
    DeriveIn,
    MergeIn,
    MergeParentIn,
)
from app.modules.production.schemas.execution import (
    EquipmentSnapshotOut,
    ExecutionCompleteIn,
    ExecutionOut,
    ExecutionStartIn,
    FieldValueIn,
    FieldValueOut,
    NodeExecutionListItem,
)
from app.modules.production.schemas.intermediate import (
    IntermediateConsumptionIn,
    IntermediateConsumptionOut,
    IntermediateOutputIn,
    IntermediateOutputOut,
    IntermediateTypeCreate,
    IntermediateTypeOut,
    IntermediateTypeUpdate,
    MaterialMovement,
    MaterialMovementsOut,
    MaterialStockSummary,
    NodeIntermediateIn,
    NodeIntermediateOut,
)
from app.modules.production.schemas.product import (
    ProductCreate,
    ProductOut,
    ProductUpdate,
)
from app.modules.production.schemas.route import (
    EdgeIn,
    EdgeOut,
    FieldDefIn,
    FieldDefOut,
    NodeIn,
    NodeOut,
    RouteCreate,
    RouteGraphIn,
    RouteGraphOut,
    RouteOut,
)
from app.modules.production.schemas.trace import (
    TraceBatch,
    TraceExecutionBrief,
    TraceLink,
    TraceOut,
)

__all__ = [
    "BatchCreate",
    "BatchDetailOut",
    "BatchOut",
    "ChildBatchIn",
    "DeriveIn",
    "EdgeIn",
    "EdgeOut",
    "EquipmentSnapshotOut",
    "ExecutionCompleteIn",
    "ExecutionOut",
    "ExecutionStartIn",
    "FieldDefIn",
    "FieldDefOut",
    "FieldValueIn",
    "FieldValueOut",
    "IntermediateConsumptionIn",
    "IntermediateConsumptionOut",
    "IntermediateOutputIn",
    "IntermediateOutputOut",
    "IntermediateTypeCreate",
    "IntermediateTypeOut",
    "IntermediateTypeUpdate",
    "MaterialMovement",
    "MaterialMovementsOut",
    "MaterialStockSummary",
    "MergeIn",
    "MergeParentIn",
    "NodeExecutionListItem",
    "NodeIn",
    "NodeIntermediateIn",
    "NodeIntermediateOut",
    "NodeOut",
    "ProductCreate",
    "ProductOut",
    "ProductUpdate",
    "RouteCreate",
    "RouteGraphIn",
    "RouteGraphOut",
    "RouteOut",
    "TraceBatch",
    "TraceExecutionBrief",
    "TraceLink",
    "TraceOut",
]
