"""add equipment tables

Revision ID: 3093dedbc980
Revises: 20260529_0001
Create Date: 2026-06-02 09:26:11.908817
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3093dedbc980'
down_revision: Union[str, None] = '20260529_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_categories',
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='分类代码'),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='父分类ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment.equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_equipment_categories_code'),
    schema='equipment'
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=100), nullable=False, comment='位置名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='位置代码'),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='父位置ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='位置描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment.locations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_locations_code'),
    schema='equipment'
    )
    op.create_table('equipments',
    sa.Column('equipment_no', sa.String(length=50), nullable=False, comment='设备编号'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='设备名称'),
    sa.Column('category_id', sa.Uuid(), nullable=False, comment='设备分类'),
    sa.Column('location_id', sa.Uuid(), nullable=False, comment='设备位置'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='设备状态：在用/备用/维修中/停用/报废'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='设备型号'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='设备规格'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='制造商'),
    sa.Column('supplier', sa.String(length=200), nullable=True, comment='供应商'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='出厂日期'),
    sa.Column('commissioning_date', sa.Date(), nullable=True, comment='投用日期'),
    sa.Column('description', sa.Text(), nullable=True, comment='设备描述'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("status IN ('在用', '备用', '维修中', '停用', '报废')", name='ck_equipments_status'),
    sa.ForeignKeyConstraint(['category_id'], ['equipment.equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['equipment.locations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_no', 'is_deleted', name='uq_equipments_equipment_no'),
    schema='equipment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipments', schema='equipment')
    op.drop_table('locations', schema='equipment')
    op.drop_table('equipment_categories', schema='equipment')
    # ### end Alembic commands ###
