"""add department_id to equipments

Revision ID: 44765a397e77
Revises: dcb4574b9b80
Create Date: 2026-06-10 16:43:55.861840
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44765a397e77'
down_revision: Union[str, None] = 'dcb4574b9b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('department_id', sa.Uuid(), nullable=True, comment='归属部门ID，逻辑引用 identity.departments.id'), schema='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'department_id', schema='equipment')
    # ### end Alembic commands ###
