"""add departments table and expand user department fields

Revision ID: 62d4ceac12b4
Revises: a7b8c9d0e1f2
Create Date: 2026-06-07 14:24:48.728860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62d4ceac12b4'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('feishu_department_id', sa.String(length=64), nullable=False, comment='飞书部门 open_department_id'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='部门名称'),
    sa.Column('parent_feishu_department_id', sa.String(length=64), nullable=True, comment='父部门 ID'),
    sa.Column('leader_user_id', sa.String(length=128), nullable=True, comment='部门主管 user_id'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='部门成员数'),
    sa.Column('status_is_deleted', sa.Boolean(), nullable=True, comment='飞书侧是否已删除'),
    sa.Column('path', sa.Text(), nullable=True, comment='部门路径 JSON，如 [{"name":"公司","id":"xxx"},...]'),
    sa.Column('order', sa.Integer(), nullable=True, comment='同级排序'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_department_id'),
    sa.UniqueConstraint('feishu_department_id', name='uq_identity_departments_feishu_id'),
    schema='identity'
    )
    op.create_table('ai_workflow_configs',
    sa.Column('module_code', sa.String(length=64), nullable=False, comment='模块代码（hazard-identification / regulation / hazard 等）'),
    sa.Column('workflow_name', sa.String(length=128), nullable=False, comment='工作流名称'),
    sa.Column('workflow_description', sa.Text(), nullable=True, comment='工作流描述'),
    sa.Column('trigger_event', sa.String(length=64), nullable=True, comment='触发事件（submit / revision_created 等）'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('script_configs', sa.JSON(), nullable=True, comment='脚本配置 JSON 数组'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='排序顺序'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code', name='uq_ai_workflow_config_module_code'),
    schema='safety',
    comment='AI 工作流配置表'
    )
    op.create_table('api_call_configs',
    sa.Column('config_name', sa.String(length=128), nullable=False, comment='配置名称'),
    sa.Column('api_base_url', sa.String(length=500), nullable=False, comment='API 基础 URL'),
    sa.Column('api_key', sa.String(length=500), nullable=False, comment='API 密钥'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment='模型名称'),
    sa.Column('temperature', sa.Float(), server_default='0.1', nullable=False, comment='温度参数'),
    sa.Column('timeout_seconds', sa.Integer(), server_default='120', nullable=False, comment='超时秒数'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大 Token 数'),
    sa.Column('extra_config', sa.JSON(), nullable=True, comment='额外配置 JSON（system_role 覆盖等）'),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False, comment='是否激活'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety',
    comment='API 调用配置表'
    )
    op.create_table('contractors',
    sa.Column('contractor_no', sa.String(length=64), nullable=False, comment='承包商编号'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='公司名称'),
    sa.Column('legal_representative', sa.String(length=100), nullable=True, comment='法定代表人'),
    sa.Column('contact_person', sa.String(length=100), nullable=False, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'),
    sa.Column('qualification_type', sa.String(length=32), server_default='other', nullable=False, comment='资质类型'),
    sa.Column('qualification_level', sa.String(length=16), nullable=True, comment='资质等级: grade_a/grade_b/grade_c'),
    sa.Column('qualification_cert_no', sa.String(length=100), nullable=True, comment='资质证书编号'),
    sa.Column('qualification_expiry', sa.DateTime(timezone=True), nullable=True, comment='资质有效期至'),
    sa.Column('safety_license_no', sa.String(length=100), nullable=True, comment='安全生产许可证编号'),
    sa.Column('safety_license_expiry', sa.DateTime(timezone=True), nullable=True, comment='安全生产许可证有效期'),
    sa.Column('insurance_info', sa.Text(), nullable=True, comment='保险信息'),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True, comment='保险有效期至'),
    sa.Column('safety_officer_name', sa.String(length=100), nullable=True, comment='安全负责人'),
    sa.Column('safety_officer_phone', sa.String(length=20), nullable=True, comment='安全负责人电话'),
    sa.Column('special_op_personnel', sa.JSON(), nullable=True, comment='特种作业人员列表 [{"name","cert_type","cert_no","expiry"}]'),
    sa.Column('training_status', sa.String(length=32), server_default='untrained', nullable=False, comment='培训状态: untrained/in_progress/passed/expired'),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True, comment='最近培训日期'),
    sa.Column('safety_performance_score', sa.Integer(), nullable=True, comment='安全绩效评分（0-100）'),
    sa.Column('blacklisted', sa.Boolean(), server_default='false', nullable=False, comment='是否黑名单'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='状态: active/inactive/blacklisted'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_no', name='uq_contractors_contractor_no'),
    schema='safety'
    )
    op.create_table('hazard_identifications',
    sa.Column('hazard_id_no', sa.String(length=64), nullable=False, comment='危险源编号'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='部门'),
    sa.Column('position', sa.String(length=100), nullable=False, comment='岗位'),
    sa.Column('production_step', sa.Text(), nullable=False, comment='生产步骤'),
    sa.Column('attachment_path', sa.String(length=500), nullable=True, comment='岗位资料附件路径'),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True, comment='附件原始文件名'),
    sa.Column('specific_activity', sa.Text(), nullable=True, comment='具体作业活动'),
    sa.Column('equipment_facilities', sa.Text(), nullable=True, comment='设备设施'),
    sa.Column('raw_auxiliary_materials', sa.Text(), nullable=True, comment='原辅料'),
    sa.Column('operation_frequency', sa.String(length=100), nullable=True, comment='作业频次'),
    sa.Column('operator_count', sa.Integer(), nullable=True, comment='操作人数'),
    sa.Column('hazard_type', sa.Text(), nullable=True, comment='危险类型（人机料法环）'),
    sa.Column('possible_accident', sa.Text(), nullable=True, comment='可能导致事故'),
    sa.Column('unsafe_behavior', sa.Text(), nullable=True, comment='不规范作业行为表现'),
    sa.Column('l_inherent', sa.Float(), nullable=True, comment='可能性L（固有）'),
    sa.Column('e_inherent', sa.Float(), nullable=True, comment='暴露频率E（固有）'),
    sa.Column('c_inherent', sa.Float(), nullable=True, comment='严重性C（固有）'),
    sa.Column('d_inherent', sa.Float(), nullable=True, comment='风险值D（固有）'),
    sa.Column('inherent_risk_level', sa.String(length=20), nullable=True, comment='固有风险等级'),
    sa.Column('inherent_risk_label', sa.String(length=50), nullable=True, comment='固有风险等级中文名'),
    sa.Column('existing_engineering_controls', sa.Text(), nullable=True, comment='现有工程控制措施'),
    sa.Column('existing_management_controls', sa.Text(), nullable=True, comment='现有管理控制措施'),
    sa.Column('existing_ppe', sa.Text(), nullable=True, comment='现有个人防护措施'),
    sa.Column('existing_emergency_measures', sa.Text(), nullable=True, comment='现有应急措施'),
    sa.Column('l_residual', sa.Float(), nullable=True, comment='可能性L（残余）'),
    sa.Column('e_residual', sa.Float(), nullable=True, comment='暴露频率E（残余）'),
    sa.Column('c_residual', sa.Float(), nullable=True, comment='严重性C（残余）'),
    sa.Column('d_residual', sa.Float(), nullable=True, comment='风险值D（残余）'),
    sa.Column('residual_risk_level', sa.String(length=20), nullable=True, comment='残余风险等级'),
    sa.Column('residual_risk_label', sa.String(length=50), nullable=True, comment='残余风险等级中文名'),
    sa.Column('needs_recommendation', sa.String(length=20), nullable=True, comment='是否需提出建议措施（是/否/待人工确认）'),
    sa.Column('recommendation_type', sa.String(length=100), nullable=True, comment='建议措施类型'),
    sa.Column('recommendation_content', sa.Text(), nullable=True, comment='建议措施内容'),
    sa.Column('recommendation_priority', sa.String(length=10), nullable=True, comment='建议措施优先级（高/中/低）'),
    sa.Column('l_post', sa.Float(), nullable=True, comment='可能性L（建议措施后）'),
    sa.Column('e_post', sa.Float(), nullable=True, comment='暴露频率E（建议措施后）'),
    sa.Column('c_post', sa.Float(), nullable=True, comment='严重性C（建议措施后）'),
    sa.Column('d_post', sa.Float(), nullable=True, comment='风险值D（建议措施后）'),
    sa.Column('post_risk_level', sa.String(length=20), nullable=True, comment='建议措施后风险等级'),
    sa.Column('post_risk_label', sa.String(length=50), nullable=True, comment='建议措施后风险等级中文名'),
    sa.Column('control_level', sa.String(length=50), nullable=True, comment='管控层级（公司级/部门级/班组级）'),
    sa.Column('responsible_person', sa.String(length=100), nullable=True, comment='责任人'),
    sa.Column('ai_node_progress', sa.String(length=50), server_default='pending_input', nullable=False, comment='AI流程节点进度'),
    sa.Column('ai_error_message', sa.Text(), nullable=True, comment='AI 脚本执行错误信息'),
    sa.Column('overall_status', sa.String(length=20), server_default='draft', nullable=False, comment='整体状态（draft/in_progress/completed/cancelled）'),
    sa.Column('script1_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本1审核状态'),
    sa.Column('script2_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本2审核状态'),
    sa.Column('script3_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本3审核状态'),
    sa.Column('script4_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本4审核状态'),
    sa.Column('script5_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本5审核状态'),
    sa.Column('script6_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本6审核状态'),
    sa.Column('script7_review_status', sa.String(length=20), server_default='pending', nullable=False, comment='脚本7审核状态'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='更新人'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hazard_id_no', name='uq_hazard_identifications_no'),
    schema='safety'
    )
    op.create_table('hazard_revision_archives',
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='对应的操规名称'),
    sa.Column('hazard_document_path', sa.String(length=500), nullable=True, comment='最新危险源辨识文档路径'),
    sa.Column('hazard_document_original_name', sa.String(length=255), nullable=True, comment='文档原始文件名'),
    sa.Column('identification_date', sa.DateTime(timezone=True), nullable=False, comment='最后辨识日期'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='状态: active/archived'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('knowledge_articles',
    sa.Column('title', sa.String(length=255), nullable=False, comment='文章标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文内容'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('category', sa.String(length=32), server_default='other', nullable=False, comment='分类'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态: draft/published/archived'),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False, comment='浏览次数'),
    sa.Column('attachment_path', sa.String(length=500), nullable=True, comment='附件路径'),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True, comment='附件原始文件名'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='更新人'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('oh_hazard_monitors',
    sa.Column('monitor_no', sa.String(length=64), nullable=False, comment='监测编号'),
    sa.Column('workplace', sa.String(length=255), nullable=False, comment='监测场所/车间'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='具体监测点位'),
    sa.Column('equipment_info', sa.String(length=255), nullable=True, comment='关联设备/岗位'),
    sa.Column('detection_type', sa.String(length=32), nullable=False, comment='检测类型: regular/commissioned/evaluation/accident'),
    sa.Column('detection_date', sa.DateTime(timezone=True), nullable=True, comment='检测日期'),
    sa.Column('detection_agency', sa.String(length=255), nullable=True, comment='检测机构'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态'),
    sa.Column('inspector_name', sa.String(length=100), nullable=True, comment='检测人员'),
    sa.Column('verifier_name', sa.String(length=100), nullable=True, comment='验证人员'),
    sa.Column('detection_results', sa.JSON(), nullable=True, comment='检测结果 JSON数组 [{factor_name, factor_category, detection_value, unit, oel_limit, compliance_status, sampling_method, standard_ref}]'),
    sa.Column('abnormality_records', sa.JSON(), nullable=True, comment='异常处置记录 JSON数组 [{abnormality_desc, corrective_action, responsible_person, deadline, status, completed_at, remarks}]'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表 JSON数组 [{name, path}]'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_no', name='uq_oh_hazard_monitors_monitor_no'),
    schema='safety',
    comment='职业危害因素监测表'
    )
    op.create_table('oh_health_exams',
    sa.Column('exam_no', sa.String(length=64), nullable=False, comment='体检编号'),
    sa.Column('employee_name', sa.String(length=100), nullable=False, comment='员工姓名'),
    sa.Column('employee_id', sa.String(length=64), nullable=True, comment='工号'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('job_position', sa.String(length=100), nullable=True, comment='岗位'),
    sa.Column('exam_type', sa.String(length=32), nullable=False, comment='体检类型: pre_employment/periodic/post_employment/emergency'),
    sa.Column('status', sa.String(length=32), server_default='scheduled', nullable=False, comment='状态'),
    sa.Column('exam_agency', sa.String(length=255), nullable=True, comment='体检机构'),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True, comment='计划体检日期'),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True, comment='实际体检日期'),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True, comment='报告日期'),
    sa.Column('hazard_factors', sa.JSON(), nullable=True, comment='关联的危害因素列表 [string]'),
    sa.Column('overall_conclusion', sa.String(length=32), nullable=True, comment='综合体检结论'),
    sa.Column('exam_items', sa.JSON(), nullable=True, comment='体检项目结果 JSON数组 [{item_name, category, result, reference_range, is_abnormal, remarks}]'),
    sa.Column('abnormality_records', sa.JSON(), nullable=True, comment='异常处置记录 JSON数组'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_no', name='uq_oh_health_exams_exam_no'),
    schema='safety',
    comment='职业健康体检表'
    )
    op.create_table('operation_regulations',
    sa.Column('regulation_no', sa.String(length=64), nullable=False, comment='操规编号'),
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='操规名称'),
    sa.Column('document_path', sa.String(length=500), nullable=True, comment='操规文档路径（当前最新版本）'),
    sa.Column('document_original_name', sa.String(length=255), nullable=True, comment='文档原始文件名'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='岗位（达托/达巴，逗号分隔）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regulation_no', name='uq_operation_regulations_no'),
    schema='safety'
    )
    op.create_table('special_operation_personnel',
    sa.Column('personnel_no', sa.String(length=64), nullable=False, comment='人员编号'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='所属部门'),
    sa.Column('certificate_type', sa.String(length=32), nullable=False, comment='证书类型（对应8种特殊作业）'),
    sa.Column('certificate_number', sa.String(length=100), nullable=True, comment='证书编号'),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True, comment='发证机关'),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True, comment='发证日期'),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True, comment='有效期至'),
    sa.Column('certificate_file_path', sa.String(length=500), nullable=True, comment='证书文件路径'),
    sa.Column('qualification_scope', sa.Text(), nullable=True, comment='资质范围'),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False, comment='状态: active/expired/revoked'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_no', name='uq_special_op_personnel_no'),
    schema='safety'
    )
    op.create_table('daily_risk_reports',
    sa.Column('report_no', sa.String(length=64), nullable=False, comment='报备编号'),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False, comment='报备作业日期'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='报备部门'),
    sa.Column('hazard_identification_id', sa.UUID(), nullable=True, comment='关联危险源辨识ID'),
    sa.Column('operation_description', sa.Text(), nullable=False, comment='风险作业描述'),
    sa.Column('operation_steps', sa.Text(), nullable=True, comment='作业步骤'),
    sa.Column('hazard_factors', sa.Text(), nullable=True, comment='危险因素'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: level_1/level_2/level_3/level_4'),
    sa.Column('control_measures', sa.Text(), nullable=True, comment='控制措施'),
    sa.Column('responsible_person', sa.String(length=100), nullable=True, comment='作业负责人'),
    sa.Column('operator_count', sa.Integer(), nullable=True, comment='作业人数'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='作业地点'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True, comment='计划结束时间'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='报备申请人姓名'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='审批人姓名'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态: draft/submitted/approved/rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['hazard_identification_id'], ['safety.hazard_identifications.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no', name='uq_daily_risk_reports_no'),
    schema='safety'
    )
    op.create_table('ehs_changes',
    sa.Column('change_no', sa.String(length=64), nullable=False, comment='变更编号'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='变更标题'),
    sa.Column('change_type', sa.String(length=32), nullable=False, comment='变更类型: process_tech/equipment_facility/management'),
    sa.Column('change_grade', sa.String(length=16), server_default='general', nullable=False, comment='变更等级: major/general'),
    sa.Column('change_duration', sa.String(length=16), server_default='permanent', nullable=False, comment='变更期限: permanent/temporary/emergency'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='申请部门'),
    sa.Column('location_unit', sa.String(length=255), nullable=True, comment='所在单元/装置'),
    sa.Column('description', sa.Text(), nullable=True, comment='变更描述（变更前/变更后对比）'),
    sa.Column('technical_basis', sa.Text(), nullable=True, comment='变更技术依据'),
    sa.Column('expected_start', sa.DateTime(timezone=True), nullable=True, comment='预期开始日期'),
    sa.Column('expected_completion', sa.DateTime(timezone=True), nullable=True, comment='预期完成日期'),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True, comment='实际开始日期'),
    sa.Column('actual_completion', sa.DateTime(timezone=True), nullable=True, comment='实际完成日期'),
    sa.Column('expected_effect', sa.Text(), nullable=True, comment='预期效果'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态'),
    sa.Column('applicant_id', sa.UUID(), nullable=True, comment='申请人ID'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='申请人姓名'),
    sa.Column('equipment_tags', sa.JSON(), nullable=True, comment='关联设备位号 JSON数组'),
    sa.Column('documents_to_update', sa.JSON(), nullable=True, comment='需更新的文件清单 JSON数组 [{name, number}]'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表 JSON数组 [{name, path}]'),
    sa.Column('risk_assessments', sa.JSON(), nullable=True, comment='风险评估 JSON数组 [{method, severity, likelihood, risk_level, description, control_measures, assessed_by, assessed_date, participants}]'),
    sa.Column('approval_chain', sa.JSON(), nullable=True, comment='审批链 JSON数组 [{level, approver_role, approver, decision, comments, decided_at}]'),
    sa.Column('action_items', sa.JSON(), nullable=True, comment='行动项 JSON数组 [{task, owner, due_date, status, completed_at}]'),
    sa.Column('pssr_checklist', sa.JSON(), nullable=True, comment='PSSR清单 JSON数组 [{item, result, checked_by, checked_at, remarks}]'),
    sa.Column('verification', sa.JSON(), nullable=True, comment='变更验证 {expected_effect_achieved, comments, psi_updated, documents_updated, accepted_by, accepted_date}'),
    sa.Column('closure', sa.JSON(), nullable=True, comment='变更关闭 {closed_by, closed_date, temp_expiry_date, restored_date}'),
    sa.Column('linked_safety_check_id', sa.UUID(), nullable=True, comment='关联安全检查ID（变更验收）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['linked_safety_check_id'], ['safety.safety_checks.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_no', name='uq_ehs_changes_change_no'),
    schema='safety',
    comment='EHS变更管理表'
    )
    op.create_table('regulation_revisions',
    sa.Column('revision_no', sa.String(length=64), nullable=False, comment='修订编号'),
    sa.Column('regulation_id', sa.UUID(), nullable=False, comment='关联操规ID'),
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='安全操规名称'),
    sa.Column('old_document_path', sa.String(length=500), nullable=True, comment='旧文档路径'),
    sa.Column('reviser', sa.UUID(), nullable=True, comment='修订人'),
    sa.Column('reviser_name', sa.String(length=100), nullable=True, comment='修订人姓名'),
    sa.Column('revision_time', sa.DateTime(timezone=True), nullable=False, comment='修订时间'),
    sa.Column('revision_type', sa.String(length=32), server_default='manual', nullable=False, comment='修订类型: manual/ai'),
    sa.Column('revision_opinion', sa.Text(), nullable=True, comment='修订意见/内容'),
    sa.Column('revision_scope', sa.String(length=100), nullable=True, comment='修订范围（逗号分隔: process/safety_requirement）'),
    sa.Column('review_opinion', sa.String(length=32), server_default='pending', nullable=False, comment='审核意见: pending/approved'),
    sa.Column('new_document_path', sa.String(length=500), nullable=True, comment='新文档路径'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['safety.operation_regulations.id'], ),
    sa.ForeignKeyConstraint(['reviser'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_no', name='uq_regulation_revisions_no'),
    schema='safety'
    )
    op.create_table('special_operation_permits',
    sa.Column('permit_no', sa.String(length=64), nullable=False, comment='作业票编号'),
    sa.Column('operation_type', sa.String(length=32), nullable=False, comment='作业类型（8种）'),
    sa.Column('operation_level', sa.String(length=16), server_default='grade2', nullable=False, comment='作业级别: special/grade1/grade2'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='作业地点'),
    sa.Column('equipment_tag', sa.String(length=100), nullable=True, comment='设备位号'),
    sa.Column('work_description', sa.Text(), nullable=True, comment='作业内容描述'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True, comment='计划结束时间'),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True, comment='实际开始时间'),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True, comment='实际结束时间'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='申请人姓名'),
    sa.Column('work_leader_name', sa.String(length=100), nullable=True, comment='作业负责人姓名'),
    sa.Column('operator_names', sa.Text(), nullable=True, comment='作业人员姓名（逗号分隔）'),
    sa.Column('guardian_name', sa.String(length=100), nullable=True, comment='监护人姓名'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='审批人姓名'),
    sa.Column('safety_measures', sa.Text(), nullable=True, comment='安全措施'),
    sa.Column('emergency_equipment', sa.Text(), nullable=True, comment='应急消防器材'),
    sa.Column('gas_analysis', sa.Text(), nullable=True, comment='气体分析结果'),
    sa.Column('risk_assessment', sa.Text(), nullable=True, comment='风险评估'),
    sa.Column('safety_briefing_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='安全交底确认'),
    sa.Column('safety_briefing_time', sa.DateTime(timezone=True), nullable=True, comment='安全交底时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('completion_method', sa.String(length=32), nullable=True, comment='完工方式: normal/early_termination'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态'),
    sa.Column('check_id', sa.UUID(), nullable=True, comment='关联安全检查ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['safety.safety_checks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_no', name='uq_special_op_permits_permit_no'),
    schema='safety'
    )
    op.create_table('contractor_work_records',
    sa.Column('contractor_id', sa.UUID(), nullable=False, comment='关联承包商ID'),
    sa.Column('work_content', sa.Text(), nullable=False, comment='施工内容'),
    sa.Column('work_location', sa.String(length=255), nullable=True, comment='施工地点'),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False, comment='计划开始时间'),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False, comment='计划结束时间'),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True, comment='实际开始时间'),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True, comment='实际结束时间'),
    sa.Column('permit_id', sa.UUID(), nullable=True, comment='关联特殊作业票ID'),
    sa.Column('leading_person', sa.String(length=100), nullable=True, comment='带班负责人'),
    sa.Column('worker_count', sa.Integer(), nullable=True, comment='施工人数'),
    sa.Column('safety_briefing_done', sa.Boolean(), server_default='false', nullable=False, comment='安全交底确认'),
    sa.Column('violations', sa.JSON(), nullable=True, comment='违章记录 [{"date","description","severity","handler","result"}]'),
    sa.Column('evaluation', sa.JSON(), nullable=True, comment='评价 {"score","comments","evaluator","date"}'),
    sa.Column('status', sa.String(length=32), server_default='in_progress', nullable=False, comment='状态: in_progress/completed/evaluated'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['safety.contractors.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['safety.special_operation_permits.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('hazard_revision_records',
    sa.Column('hazard_revision_no', sa.String(length=64), nullable=False, comment='危险源辨识修订编号'),
    sa.Column('regulation_revision_id', sa.UUID(), nullable=True, comment='关联操规修订记录ID'),
    sa.Column('regulation_name', sa.String(length=255), nullable=False, comment='对应的操规名称'),
    sa.Column('identifier_id', sa.UUID(), nullable=True, comment='辨识人'),
    sa.Column('identifier_name', sa.String(length=100), nullable=True, comment='辨识人姓名'),
    sa.Column('identification_time', sa.DateTime(timezone=True), nullable=False, comment='辨识时间'),
    sa.Column('identification_type', sa.String(length=32), server_default='auto_trigger', nullable=False, comment='辨识类型: auto_trigger/manual_start'),
    sa.Column('process_change_content', sa.Text(), nullable=True, comment='涉及工艺变更内容'),
    sa.Column('identification_scope', sa.String(length=200), nullable=True, comment='辨识范围（逗号分隔: 人/机/料/法/环）'),
    sa.Column('review_opinion', sa.String(length=32), server_default='pending', nullable=False, comment='审核意见: pending/approved/rejected'),
    sa.Column('hazard_document_path', sa.String(length=500), nullable=True, comment='危险源辨识文档路径'),
    sa.Column('hazard_document_original_name', sa.String(length=255), nullable=True, comment='文档原始文件名'),
    sa.Column('linked_hazard_archive_id', sa.UUID(), nullable=True, comment='关联的危险源辨识存档ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['identifier_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['linked_hazard_archive_id'], ['safety.hazard_revision_archives.id'], ),
    sa.ForeignKeyConstraint(['regulation_revision_id'], ['safety.regulation_revisions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hazard_revision_no', name='uq_hazard_revision_records_no'),
    schema='safety'
    )
    op.create_table('special_operation_reports',
    sa.Column('report_no', sa.String(length=64), nullable=False, comment='报备编号'),
    sa.Column('permit_id', sa.UUID(), nullable=True, comment='关联作业票ID'),
    sa.Column('operation_type', sa.String(length=32), nullable=False, comment='作业类型（8种）'),
    sa.Column('operation_level', sa.String(length=16), server_default='grade2', nullable=False, comment='作业级别: special/grade1/grade2'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='报备部门'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='作业地点'),
    sa.Column('equipment_tag', sa.String(length=100), nullable=True, comment='设备位号'),
    sa.Column('work_description', sa.Text(), nullable=True, comment='作业内容描述'),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True, comment='计划开始时间'),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True, comment='计划结束时间'),
    sa.Column('work_leader_name', sa.String(length=100), nullable=True, comment='作业负责人姓名'),
    sa.Column('operator_names', sa.Text(), nullable=True, comment='作业人员姓名（逗号分隔）'),
    sa.Column('guardian_name', sa.String(length=100), nullable=True, comment='监护人姓名'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: level_1/level_2/level_3/level_4'),
    sa.Column('safety_measures', sa.Text(), nullable=True, comment='安全措施'),
    sa.Column('emergency_equipment', sa.Text(), nullable=True, comment='应急消防器材'),
    sa.Column('gas_analysis', sa.Text(), nullable=True, comment='气体分析结果'),
    sa.Column('risk_assessment', sa.Text(), nullable=True, comment='风险评估描述'),
    sa.Column('applicant_name', sa.String(length=100), nullable=True, comment='报备申请人姓名'),
    sa.Column('approver_name', sa.String(length=100), nullable=True, comment='审批人姓名'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='审批时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False, comment='状态: draft/submitted/approved/rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['safety.special_operation_permits.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no', name='uq_special_operation_reports_no'),
    schema='safety'
    )
    op.alter_column('inspection_records', 'task_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='关联巡检任务ID',
               schema='equipment')
    op.alter_column('inspection_tasks', 'equipment_id',
               existing_type=sa.UUID(),
               comment='单设备ID（单设备模式，兼容旧数据）',
               existing_comment='单设备ID（单设备模式）',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_tasks', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='巡检类型：日常巡检/周巡检/月巡检/专项巡检',
               existing_comment='巡检类型',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态：待执行/执行中/已完成/已关闭',
               existing_comment='任务状态',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'overall_result',
               existing_type=sa.VARCHAR(length=10),
               comment='总体结果：正常/异常',
               existing_comment='总体结果',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：待处理/执行中/待验收/已完成/已关闭',
               existing_comment='状态：待处理/已指派/维修中/待验收/已完成/已关闭',
               existing_nullable=False,
               schema='equipment')
    op.add_column('users', sa.Column('feishu_department_ids', sa.Text(), nullable=True, comment='飞书部门ID列表，JSON数组'), schema='identity')
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='identity')
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True,
               schema='identity')
    op.drop_column('users', 'feishu_department_id', schema='identity')
    op.add_column('accidents', sa.Column('department', sa.String(length=100), nullable=True, comment='发生部门'), schema='safety')
    op.add_column('accidents', sa.Column('loss_work_days', sa.Integer(), nullable=True, comment='损失工作日'), schema='safety')
    op.add_column('accidents', sa.Column('injury_details', sa.JSON(), nullable=True, comment='伤员详情 JSON [{"name","position","injury_part","severity","hospital"}]'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_team', sa.JSON(), nullable=True, comment='调查组 JSON [{"name","role"}]'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_method', sa.String(length=100), nullable=True, comment='调查方法: 5-Why/FTA/Event Tree/BowTie等'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_findings', sa.Text(), nullable=True, comment='调查发现'), schema='safety')
    op.add_column('accidents', sa.Column('investigation_report_path', sa.String(length=500), nullable=True, comment='调查报告文件路径'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_deadline', sa.DateTime(timezone=True), nullable=True, comment='CAPA截止日期'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_responsible', sa.String(length=100), nullable=True, comment='CAPA责任人'), schema='safety')
    op.add_column('accidents', sa.Column('corrective_action_status', sa.String(length=32), nullable=True, comment='CAPA状态: pending/in_progress/completed/verified'), schema='safety')
    op.add_column('accidents', sa.Column('verified_by', sa.UUID(), nullable=True, comment='CAPA验证人'), schema='safety')
    op.add_column('accidents', sa.Column('verified_by_name', sa.String(length=100), nullable=True, comment='验证人姓名'), schema='safety')
    op.add_column('accidents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='验证时间'), schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况汇总',
               existing_comment='伤亡情况',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.create_foreign_key(None, 'accidents', 'users', ['verified_by'], ['id'], source_schema='safety', referent_schema='identity')
    op.add_column('hazard_reports', sa.Column('hazard_category', sa.String(length=32), nullable=True, comment='隐患类别（设备设施/危化储存…）'), schema='safety')
    op.add_column('hazard_reports', sa.Column('major_hazard_basis', sa.Text(), nullable=True, comment='重大隐患判定依据'), schema='safety')
    op.add_column('hazard_reports', sa.Column('key_defect', sa.String(length=100), nullable=True, comment='重点缺陷'), schema='safety')
    op.add_column('hazard_reports', sa.Column('defect_photos', sa.Text(), nullable=True, comment='缺陷图片JSON数组'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_responsible_person_name', sa.String(length=100), nullable=True, comment='整改责任人姓名'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_responsible_department', sa.String(length=100), nullable=True, comment='整改责任人部门'), schema='safety')
    op.add_column('hazard_reports', sa.Column('corrective_preventive_measures', sa.Text(), nullable=True, comment='纠正预防措施'), schema='safety')
    op.add_column('hazard_reports', sa.Column('actual_completion_date', sa.DateTime(timezone=True), nullable=True, comment='实际完成时间'), schema='safety')
    op.add_column('hazard_reports', sa.Column('extended_deadline', sa.DateTime(timezone=True), nullable=True, comment='延期完成日期'), schema='safety')
    op.add_column('hazard_reports', sa.Column('rectification_photos', sa.Text(), nullable=True, comment='整改后图片JSON数组'), schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患分类（人/物/环/管）',
               existing_comment='隐患类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级（一般/较大/重大）',
               existing_comment='隐患等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='计划完成时间',
               existing_comment='整改期限',
               existing_nullable=True,
               schema='safety')
    op.add_column('safety_checks', sa.Column('inspector_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='检查人员确认'), schema='safety')
    op.add_column('safety_checks', sa.Column('safety_officer_confirmed', sa.Boolean(), server_default='false', nullable=False, comment='安全办确认'), schema='safety')
    op.add_column('safety_trainings', sa.Column('training_level', sa.String(length=32), server_default='dept', nullable=False, comment='培训级别: company/dept/team'), schema='safety')
    op.add_column('safety_trainings', sa.Column('exam_passing_score', sa.Float(), server_default='60', nullable=True, comment='及格分数线'), schema='safety')
    op.add_column('safety_trainings', sa.Column('course_material_path', sa.String(length=500), nullable=True, comment='课程资料路径'), schema='safety')
    op.add_column('training_records', sa.Column('position', sa.String(length=100), nullable=True, comment='岗位'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_no', sa.String(length=100), nullable=True, comment='证书编号'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_expiry', sa.DateTime(timezone=True), nullable=True, comment='证书有效期至'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_status', sa.String(length=32), nullable=True, comment='证书状态: valid/expiring/expired'), schema='safety')
    op.add_column('training_records', sa.Column('certificate_file_path', sa.String(length=500), nullable=True, comment='证书文件路径'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_records', 'certificate_file_path', schema='safety')
    op.drop_column('training_records', 'certificate_status', schema='safety')
    op.drop_column('training_records', 'certificate_expiry', schema='safety')
    op.drop_column('training_records', 'certificate_no', schema='safety')
    op.drop_column('training_records', 'position', schema='safety')
    op.drop_column('safety_trainings', 'course_material_path', schema='safety')
    op.drop_column('safety_trainings', 'exam_passing_score', schema='safety')
    op.drop_column('safety_trainings', 'training_level', schema='safety')
    op.drop_column('safety_checks', 'safety_officer_confirmed', schema='safety')
    op.drop_column('safety_checks', 'inspector_confirmed', schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='整改期限',
               existing_comment='计划完成时间',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级',
               existing_comment='隐患等级（一般/较大/重大）',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患类型',
               existing_comment='隐患分类（人/物/环/管）',
               existing_nullable=False,
               schema='safety')
    op.drop_column('hazard_reports', 'rectification_photos', schema='safety')
    op.drop_column('hazard_reports', 'extended_deadline', schema='safety')
    op.drop_column('hazard_reports', 'actual_completion_date', schema='safety')
    op.drop_column('hazard_reports', 'corrective_preventive_measures', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_department', schema='safety')
    op.drop_column('hazard_reports', 'rectification_responsible_person_name', schema='safety')
    op.drop_column('hazard_reports', 'defect_photos', schema='safety')
    op.drop_column('hazard_reports', 'key_defect', schema='safety')
    op.drop_column('hazard_reports', 'major_hazard_basis', schema='safety')
    op.drop_column('hazard_reports', 'hazard_category', schema='safety')
    op.drop_constraint(None, 'accidents', schema='safety', type_='foreignkey')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_comment='状态: reported/investigating/investigated/capa_in_progress/closed',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况',
               existing_comment='伤亡情况汇总',
               existing_nullable=True,
               schema='safety')
    op.drop_column('accidents', 'verified_at', schema='safety')
    op.drop_column('accidents', 'verified_by_name', schema='safety')
    op.drop_column('accidents', 'verified_by', schema='safety')
    op.drop_column('accidents', 'corrective_action_status', schema='safety')
    op.drop_column('accidents', 'corrective_action_responsible', schema='safety')
    op.drop_column('accidents', 'corrective_action_deadline', schema='safety')
    op.drop_column('accidents', 'investigation_report_path', schema='safety')
    op.drop_column('accidents', 'investigation_findings', schema='safety')
    op.drop_column('accidents', 'investigation_method', schema='safety')
    op.drop_column('accidents', 'investigation_team', schema='safety')
    op.drop_column('accidents', 'injury_details', schema='safety')
    op.drop_column('accidents', 'loss_work_days', schema='safety')
    op.drop_column('accidents', 'department', schema='safety')
    op.add_column('users', sa.Column('feishu_department_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='飞书部门ID'), schema='identity')
    op.alter_column('users', 'position',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='identity')
    op.alter_column('users', 'department',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               schema='identity')
    op.drop_column('users', 'feishu_department_ids', schema='identity')
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：待处理/已指派/维修中/待验收/已完成/已关闭',
               existing_comment='状态：待处理/执行中/待验收/已完成/已关闭',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'overall_result',
               existing_type=sa.VARCHAR(length=10),
               comment='总体结果',
               existing_comment='总体结果：正常/异常',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_comment='任务状态：待执行/执行中/已完成/已关闭',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               comment='巡检类型',
               existing_comment='巡检类型：日常巡检/周巡检/月巡检/专项巡检',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_tasks', 'equipment_id',
               existing_type=sa.UUID(),
               comment='单设备ID（单设备模式）',
               existing_comment='单设备ID（单设备模式，兼容旧数据）',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_records', 'task_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='关联巡检任务ID',
               schema='equipment')
    op.drop_table('special_operation_reports', schema='safety')
    op.drop_table('hazard_revision_records', schema='safety')
    op.drop_table('contractor_work_records', schema='safety')
    op.drop_table('special_operation_permits', schema='safety')
    op.drop_table('regulation_revisions', schema='safety')
    op.drop_table('ehs_changes', schema='safety')
    op.drop_table('daily_risk_reports', schema='safety')
    op.drop_table('special_operation_personnel', schema='safety')
    op.drop_table('operation_regulations', schema='safety')
    op.drop_table('oh_health_exams', schema='safety')
    op.drop_table('oh_hazard_monitors', schema='safety')
    op.drop_table('knowledge_articles', schema='safety')
    op.drop_table('hazard_revision_archives', schema='safety')
    op.drop_table('hazard_identifications', schema='safety')
    op.drop_table('contractors', schema='safety')
    op.drop_table('api_call_configs', schema='safety')
    op.drop_table('ai_workflow_configs', schema='safety')
    op.drop_table('departments', schema='identity')
    # ### end Alembic commands ###
