"""add responsible_person_id to equipments

Revision ID: 63cd22be7097
Revises: 786aeafd60da
Create Date: 2026-06-11 11:13:33.229158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cd22be7097'
down_revision: Union[str, None] = '786aeafd60da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='负责人ID，逻辑引用 identity.users.id；未设置时由部门负责人推导'), schema='equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipments', 'responsible_person_id', schema='equipment')
    # ### end Alembic commands ###
