"""add spare parts tables

Revision ID: 8669b3dc5093
Revises: e2001a3b5c77
Create Date: 2026-06-04 14:59:38.184775
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8669b3dc5093'
down_revision: Union[str, None] = 'e2001a3b5c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spare_parts',
    sa.Column('code', sa.String(length=50), nullable=False, comment='备件编码'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='备件名称'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='备件分类'),
    sa.Column('default_supplier', sa.String(length=200), nullable=True, comment='默认供应商'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='参考单价'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'is_deleted', name='uq_spare_parts_code'),
    schema='equipment'
    )
    op.create_table('spare_part_stocks',
    sa.Column('spare_part_id', sa.Uuid(), nullable=False, comment='备件ID'),
    sa.Column('warehouse_location', sa.String(length=100), nullable=True, comment='库位'),
    sa.Column('current_qty', sa.Integer(), server_default='0', nullable=False, comment='当前库存'),
    sa.Column('safety_qty', sa.Integer(), server_default='0', nullable=False, comment='安全库存'),
    sa.Column('min_order_qty', sa.Integer(), server_default='1', nullable=False, comment='最小采购批量'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['equipment.spare_parts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spare_part_id'),
    schema='equipment'
    )
    op.create_table('equipment_spare_parts',
    sa.Column('equipment_id', sa.Uuid(), nullable=False, comment='设备ID'),
    sa.Column('spare_part_id', sa.Uuid(), nullable=False, comment='备件ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='该设备需要的数量'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipments.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['equipment.spare_parts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'spare_part_id', 'is_deleted', name='uq_equipment_spare_parts_eq_sp'),
    schema='equipment'
    )
    op.create_table('spare_part_transactions',
    sa.Column('spare_part_id', sa.Uuid(), nullable=False, comment='备件ID'),
    sa.Column('work_order_id', sa.Uuid(), nullable=True, comment='关联工单ID'),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment='类型：入库/出库/盘点调整'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量（正=入库，负=出库）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("transaction_type IN ('入库', '出库', '盘点调整')", name='ck_spare_part_transactions_type'),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['spare_part_id'], ['equipment.spare_parts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['equipment.work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_part_transactions', schema='equipment')
    op.drop_table('equipment_spare_parts', schema='equipment')
    op.drop_table('spare_part_stocks', schema='equipment')
    op.drop_table('spare_parts', schema='equipment')
    # ### end Alembic commands ###
