"""add work_order_images and maintenance_config

Revision ID: 99e9cdbbe4ac
Revises: bb3e6f4ce3cf
Create Date: 2026-06-05 15:24:55.718645
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99e9cdbbe4ac'
down_revision: Union[str, None] = 'bb3e6f4ce3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_config',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.String(length=500), nullable=False, comment='配置值'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    schema='equipment'
    )
    op.create_table('work_order_images',
    sa.Column('work_order_id', sa.Uuid(), nullable=False, comment='工单ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='服务器文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='上传时间'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['equipment.work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.alter_column('inspection_records', 'work_order_id',
               existing_type=sa.UUID(),
               comment='关联巡检工单ID',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_records', 'template_item_id',
               existing_type=sa.UUID(),
               comment='检查项ID',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_records', 'result',
               existing_type=sa.VARCHAR(length=20),
               comment='结果：正常/异常/跳过',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_records', 'actual_value',
               existing_type=sa.VARCHAR(length=200),
               comment='实际值',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_records', 'remark',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='equipment')
    op.add_column('inspection_templates', sa.Column('created_by', sa.Uuid(), nullable=True), schema='equipment')
    op.add_column('inspection_templates', sa.Column('updated_by', sa.Uuid(), nullable=True), schema='equipment')
    op.create_foreign_key(None, 'inspection_templates', 'users', ['updated_by'], ['id'], source_schema='equipment', referent_schema='identity')
    op.create_foreign_key(None, 'inspection_templates', 'users', ['created_by'], ['id'], source_schema='equipment', referent_schema='identity')
    op.add_column('maintenance_plans', sa.Column('created_by', sa.Uuid(), nullable=True), schema='equipment')
    op.add_column('maintenance_plans', sa.Column('updated_by', sa.Uuid(), nullable=True), schema='equipment')
    op.alter_column('maintenance_plans', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='计划类型：预防性维护/预测性维护',
               existing_nullable=False,
               schema='equipment')
    op.create_foreign_key(None, 'maintenance_plans', 'users', ['updated_by'], ['id'], source_schema='equipment', referent_schema='identity')
    op.create_foreign_key(None, 'maintenance_plans', 'users', ['created_by'], ['id'], source_schema='equipment', referent_schema='identity')
    op.add_column('users', sa.Column('feishu_department_id', sa.String(length=64), nullable=True, comment='飞书部门ID'), schema='identity')
    op.alter_column('batch_materials', 'batch_id',
               existing_type=sa.UUID(),
               comment='批次ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('batch_materials', 'material_code',
               existing_type=sa.VARCHAR(length=64),
               comment='物料编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('batch_materials', 'material_name',
               existing_type=sa.VARCHAR(length=255),
               comment='物料名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'material_type',
               existing_type=sa.VARCHAR(length=50),
               comment='物料类型',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='单位',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'planned_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='计划用量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'actual_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='实际用量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'lot_no',
               existing_type=sa.VARCHAR(length=64),
               comment='批号/批次',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'stage',
               existing_type=sa.VARCHAR(length=50),
               comment='工序阶段',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_batch_materials_batch_id'), table_name='batch_materials', schema='production')
    op.add_column('batches', sa.Column('input_qty', sa.Float(), nullable=True, comment='实际投入数量'), schema='production')
    op.alter_column('batches', 'batch_no',
               existing_type=sa.VARCHAR(length=64),
               comment='批次号',
               existing_nullable=False,
               schema='production')
    op.alter_column('batches', 'product_code',
               existing_type=sa.VARCHAR(length=64),
               comment='产品编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('batches', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='产品名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'specification',
               existing_type=sa.VARCHAR(length=100),
               comment='规格',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='单位',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='production')
    op.alter_column('batches', 'planned_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='计划数量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'actual_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='实际产出数量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'process_spec_id',
               existing_type=sa.UUID(),
               comment='工艺规程ID',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'production_line',
               existing_type=sa.VARCHAR(length=100),
               comment='生产线',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='结束时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_batches_batch_no'), table_name='batches', schema='production')
    op.drop_index(op.f('idx_batches_product_code'), table_name='batches', schema='production')
    op.drop_index(op.f('idx_batches_status'), table_name='batches', schema='production')
    op.create_foreign_key(None, 'batches', 'process_specs', ['process_spec_id'], ['id'], source_schema='production', referent_schema='production')
    op.alter_column('material_balances', 'batch_id',
               existing_type=sa.UUID(),
               comment='批次ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('material_balances', 'input_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='投入总量',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'output_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='产出总量',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'loss_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='损耗总量',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'balance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='平衡率(%)',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'min_balance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='最低平衡率(%)',
               existing_nullable=False,
               schema='production')
    op.alter_column('material_balances', 'is_balanced',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否平衡',
               existing_nullable=False,
               schema='production')
    op.alter_column('material_balances', 'deviation_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='偏差率(%)',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='计算时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'plan_id',
               existing_type=sa.UUID(),
               comment='计划ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('plan_tasks', 'product_code',
               existing_type=sa.VARCHAR(length=64),
               comment='产品编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('plan_tasks', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='产品名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'batch_qty',
               existing_type=sa.INTEGER(),
               comment='批次数量',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'assigned_to',
               existing_type=sa.UUID(),
               comment='负责人',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'assigned_to_name',
               existing_type=sa.VARCHAR(length=100),
               comment='负责人姓名',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='计划完成日期',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='production')
    op.alter_column('plan_tasks', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_plan_tasks_plan_id'), table_name='plan_tasks', schema='production')
    op.alter_column('process_parameters', 'step_id',
               existing_type=sa.UUID(),
               comment='步骤ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_parameters', 'param_name',
               existing_type=sa.VARCHAR(length=255),
               comment='参数名称',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_parameters', 'param_code',
               existing_type=sa.VARCHAR(length=64),
               comment='参数编码',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='单位',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'min_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最小值',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'max_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='最大值',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'target_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='目标值',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'is_critical',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否关键参数',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_parameters', 'data_type',
               existing_type=sa.VARCHAR(length=20),
               comment='数据类型:numeric/text/boolean',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_process_parameters_step_id'), table_name='process_parameters', schema='production')
    op.alter_column('process_specs', 'spec_code',
               existing_type=sa.VARCHAR(length=64),
               comment='规程编号',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_specs', 'spec_name',
               existing_type=sa.VARCHAR(length=255),
               comment='规程名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'product_code',
               existing_type=sa.VARCHAR(length=64),
               comment='产品编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_specs', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment='产品名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment='版本号',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"),
               schema='production')
    op.alter_column('process_specs', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='production')
    op.alter_column('process_specs', 'effective_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生效日期',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'approved_by',
               existing_type=sa.UUID(),
               comment='批准人',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'approved_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment='批准人姓名',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='批准时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'supersedes_version',
               existing_type=sa.VARCHAR(length=20),
               comment='替代版本',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_process_specs_product_code'), table_name='process_specs', schema='production')
    op.drop_index(op.f('idx_process_specs_status'), table_name='process_specs', schema='production')
    op.alter_column('process_steps', 'spec_id',
               existing_type=sa.UUID(),
               comment='规程ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_steps', 'step_no',
               existing_type=sa.INTEGER(),
               comment='步骤序号',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_steps', 'step_name',
               existing_type=sa.VARCHAR(length=255),
               comment='步骤名称',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_steps', 'description',
               existing_type=sa.TEXT(),
               comment='步骤描述',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'equipment_type',
               existing_type=sa.VARCHAR(length=100),
               comment='设备类型',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'equipment_spec',
               existing_type=sa.VARCHAR(length=255),
               comment='设备规格',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'duration_minutes',
               existing_type=sa.INTEGER(),
               comment='持续时间(分钟)',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'sequence_order',
               existing_type=sa.INTEGER(),
               comment='排序顺序',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_process_steps_spec_id'), table_name='process_steps', schema='production')
    op.alter_column('production_plans', 'plan_no',
               existing_type=sa.VARCHAR(length=64),
               comment='计划编号',
               existing_nullable=False,
               schema='production')
    op.alter_column('production_plans', 'plan_name',
               existing_type=sa.VARCHAR(length=255),
               comment='计划名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'plan_type',
               existing_type=sa.VARCHAR(length=50),
               comment='计划类型:月计划/周计划',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'plan_month',
               existing_type=sa.VARCHAR(length=7),
               comment='计划月份YYYY-MM',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='production')
    op.alter_column('production_plans', 'total_batches',
               existing_type=sa.INTEGER(),
               comment='总批次',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'completed_batches',
               existing_type=sa.INTEGER(),
               comment='已完成批次',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_production_plans_plan_month'), table_name='production_plans', schema='production')
    op.drop_index(op.f('idx_production_plans_status'), table_name='production_plans', schema='production')
    op.alter_column('production_records', 'batch_id',
               existing_type=sa.UUID(),
               comment='批次ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('production_records', 'record_no',
               existing_type=sa.VARCHAR(length=64),
               comment='记录编号',
               existing_nullable=False,
               schema='production')
    op.alter_column('production_records', 'step_no',
               existing_type=sa.INTEGER(),
               comment='步骤序号',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'step_name',
               existing_type=sa.VARCHAR(length=255),
               comment='步骤名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'operator',
               existing_type=sa.UUID(),
               comment='操作人',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'operator_name',
               existing_type=sa.VARCHAR(length=100),
               comment='操作人姓名',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'operation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='操作时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='production')
    op.alter_column('production_records', 'operation_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               comment='操作类型',
               existing_nullable=False,
               schema='production')
    op.alter_column('production_records', 'parameters',
               existing_type=sa.TEXT(),
               comment='参数JSON',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'result',
               existing_type=sa.TEXT(),
               comment='操作结果',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'remarks',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='production')
    op.drop_index(op.f('idx_production_records_batch_id'), table_name='production_records', schema='production')
    op.drop_index(op.f('idx_production_records_operation_time'), table_name='production_records', schema='production')
    op.alter_column('accidents', 'accident_no',
               existing_type=sa.VARCHAR(length=64),
               comment='事故编号',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'accident_type',
               existing_type=sa.VARCHAR(length=32),
               comment='事故类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'accident_level',
               existing_type=sa.VARCHAR(length=32),
               comment='事故等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'happened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='发生时间',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='发生地点',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'description',
               existing_type=sa.TEXT(),
               comment='事故描述',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment='伤亡情况',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'property_damage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='财产损失(元)',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'direct_cause',
               existing_type=sa.TEXT(),
               comment='直接原因',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'root_cause',
               existing_type=sa.TEXT(),
               comment='根本原因',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'handling_measures',
               existing_type=sa.TEXT(),
               comment='处理措施',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'corrective_actions',
               existing_type=sa.TEXT(),
               comment='纠正预防措施',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.alter_column('accidents', 'reported_by',
               existing_type=sa.UUID(),
               comment='报告人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'reported_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment='报告人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'reported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='报告时间',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'investigator',
               existing_type=sa.UUID(),
               comment='调查人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'investigator_name',
               existing_type=sa.VARCHAR(length=100),
               comment='调查人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='safety')
    op.drop_index(op.f('idx_accidents_accident_no'), table_name='accidents', schema='safety')
    op.drop_index(op.f('idx_accidents_accident_type'), table_name='accidents', schema='safety')
    op.drop_index(op.f('idx_accidents_happened_at'), table_name='accidents', schema='safety')
    op.drop_index(op.f('idx_accidents_status'), table_name='accidents', schema='safety')
    op.alter_column('hazard_reports', 'hazard_no',
               existing_type=sa.VARCHAR(length=64),
               comment='隐患编号',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment='隐患类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment='隐患等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'description',
               existing_type=sa.TEXT(),
               comment='隐患描述',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='地点/部位',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'discovered_by',
               existing_type=sa.UUID(),
               comment='发现人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'discovered_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment='发现人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='发现时间',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment='责任部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'control_measures',
               existing_type=sa.TEXT(),
               comment='管控措施',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='整改期限',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'rectification_status',
               existing_type=sa.VARCHAR(length=32),
               comment='整改进度',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='safety')
    op.alter_column('hazard_reports', 'verified_by',
               existing_type=sa.UUID(),
               comment='验证人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'verified_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment='验证人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='验证时间',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"),
               schema='safety')
    op.alter_column('hazard_reports', 'check_id',
               existing_type=sa.UUID(),
               comment='关联检查ID',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='safety')
    op.drop_index(op.f('idx_hazard_reports_check_id'), table_name='hazard_reports', schema='safety')
    op.drop_index(op.f('idx_hazard_reports_department'), table_name='hazard_reports', schema='safety')
    op.drop_index(op.f('idx_hazard_reports_hazard_level'), table_name='hazard_reports', schema='safety')
    op.drop_index(op.f('idx_hazard_reports_hazard_no'), table_name='hazard_reports', schema='safety')
    op.drop_index(op.f('idx_hazard_reports_hazard_type'), table_name='hazard_reports', schema='safety')
    op.drop_index(op.f('idx_hazard_reports_status'), table_name='hazard_reports', schema='safety')
    op.alter_column('safety_checks', 'check_no',
               existing_type=sa.VARCHAR(length=64),
               comment='检查编号',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_checks', 'check_type',
               existing_type=sa.VARCHAR(length=32),
               comment='检查类型',
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::character varying"),
               schema='safety')
    op.alter_column('safety_checks', 'check_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='检查日期',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_checks', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment='检查部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'inspector',
               existing_type=sa.UUID(),
               comment='检查人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'inspector_name',
               existing_type=sa.VARCHAR(length=100),
               comment='检查人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='检查地点',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'findings',
               existing_type=sa.TEXT(),
               comment='检查发现',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'result',
               existing_type=sa.VARCHAR(length=32),
               comment='检查结果: qualified/unqualified/need_rectification',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'rectification_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否需要整改',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_checks', 'rectification_deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='整改期限',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'rectification_status',
               existing_type=sa.VARCHAR(length=32),
               comment='整改进度',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='safety')
    op.alter_column('safety_checks', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='safety')
    op.drop_index(op.f('idx_safety_checks_check_date'), table_name='safety_checks', schema='safety')
    op.drop_index(op.f('idx_safety_checks_check_no'), table_name='safety_checks', schema='safety')
    op.drop_index(op.f('idx_safety_checks_check_type'), table_name='safety_checks', schema='safety')
    op.drop_index(op.f('idx_safety_checks_status'), table_name='safety_checks', schema='safety')
    op.alter_column('safety_trainings', 'training_no',
               existing_type=sa.VARCHAR(length=64),
               comment='培训编号',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'training_name',
               existing_type=sa.VARCHAR(length=255),
               comment='培训名称',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'training_type',
               existing_type=sa.VARCHAR(length=32),
               comment='培训类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'training_mode',
               existing_type=sa.VARCHAR(length=16),
               comment='培训方式',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'trainer',
               existing_type=sa.UUID(),
               comment='培训讲师',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'trainer_name',
               existing_type=sa.VARCHAR(length=100),
               comment='讲师姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'training_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='培训日期',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'duration_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='培训时长(小时)',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='培训地点',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'content',
               existing_type=sa.TEXT(),
               comment='培训内容',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment='培训部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='safety')
    op.alter_column('safety_trainings', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='safety')
    op.drop_index(op.f('idx_safety_trainings_status'), table_name='safety_trainings', schema='safety')
    op.drop_index(op.f('idx_safety_trainings_training_date'), table_name='safety_trainings', schema='safety')
    op.drop_index(op.f('idx_safety_trainings_training_no'), table_name='safety_trainings', schema='safety')
    op.drop_index(op.f('idx_safety_trainings_training_type'), table_name='safety_trainings', schema='safety')
    op.alter_column('training_records', 'training_id',
               existing_type=sa.UUID(),
               comment='培训ID',
               existing_nullable=False,
               schema='safety')
    op.alter_column('training_records', 'employee_id',
               existing_type=sa.UUID(),
               comment='员工ID',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'employee_name',
               existing_type=sa.VARCHAR(length=100),
               comment='员工姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment='部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'attendance',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否出席',
               existing_nullable=False,
               schema='safety')
    op.alter_column('training_records', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='考核成绩',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'passed',
               existing_type=sa.BOOLEAN(),
               comment='是否合格',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'notes',
               existing_type=sa.TEXT(),
               comment='备注',
               existing_nullable=True,
               schema='safety')
    op.drop_index(op.f('idx_training_records_employee_id'), table_name='training_records', schema='safety')
    op.drop_index(op.f('idx_training_records_training_id'), table_name='training_records', schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_training_records_training_id'), 'training_records', ['training_id'], unique=False, schema='safety')
    op.create_index(op.f('idx_training_records_employee_id'), 'training_records', ['employee_id'], unique=False, schema='safety')
    op.alter_column('training_records', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'passed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否合格',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='考核成绩',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'attendance',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='是否出席',
               existing_nullable=False,
               schema='safety')
    op.alter_column('training_records', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'employee_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='员工姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'employee_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='员工ID',
               existing_nullable=True,
               schema='safety')
    op.alter_column('training_records', 'training_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='培训ID',
               existing_nullable=False,
               schema='safety')
    op.create_index(op.f('idx_safety_trainings_training_type'), 'safety_trainings', ['training_type'], unique=False, schema='safety')
    op.create_index(op.f('idx_safety_trainings_training_no'), 'safety_trainings', ['training_no'], unique=False, schema='safety')
    op.create_index(op.f('idx_safety_trainings_training_date'), 'safety_trainings', ['training_date'], unique=False, schema='safety')
    op.create_index(op.f('idx_safety_trainings_status'), 'safety_trainings', ['status'], unique=False, schema='safety')
    op.alter_column('safety_trainings', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='safety')
    op.alter_column('safety_trainings', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='培训部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='培训内容',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='培训地点',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'duration_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='培训时长(小时)',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'training_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='培训日期',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'trainer_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='讲师姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'trainer',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='培训讲师',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_trainings', 'training_mode',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='培训方式',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'training_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='培训类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'training_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='培训名称',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_trainings', 'training_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='培训编号',
               existing_nullable=False,
               schema='safety')
    op.create_index(op.f('idx_safety_checks_status'), 'safety_checks', ['status'], unique=False, schema='safety')
    op.create_index(op.f('idx_safety_checks_check_type'), 'safety_checks', ['check_type'], unique=False, schema='safety')
    op.create_index(op.f('idx_safety_checks_check_no'), 'safety_checks', ['check_no'], unique=False, schema='safety')
    op.create_index(op.f('idx_safety_checks_check_date'), 'safety_checks', ['check_date'], unique=False, schema='safety')
    op.alter_column('safety_checks', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='safety')
    op.alter_column('safety_checks', 'rectification_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='整改进度',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'rectification_deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='整改期限',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'rectification_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否需要整改',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_checks', 'result',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='检查结果: qualified/unqualified/need_rectification',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'findings',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='检查发现',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='检查地点',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'inspector_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='检查人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'inspector',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='检查人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='检查部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('safety_checks', 'check_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='检查日期',
               existing_nullable=False,
               schema='safety')
    op.alter_column('safety_checks', 'check_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='检查类型',
               existing_nullable=False,
               existing_server_default=sa.text("'daily'::character varying"),
               schema='safety')
    op.alter_column('safety_checks', 'check_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='检查编号',
               existing_nullable=False,
               schema='safety')
    op.create_index(op.f('idx_hazard_reports_status'), 'hazard_reports', ['status'], unique=False, schema='safety')
    op.create_index(op.f('idx_hazard_reports_hazard_type'), 'hazard_reports', ['hazard_type'], unique=False, schema='safety')
    op.create_index(op.f('idx_hazard_reports_hazard_no'), 'hazard_reports', ['hazard_no'], unique=False, schema='safety')
    op.create_index(op.f('idx_hazard_reports_hazard_level'), 'hazard_reports', ['hazard_level'], unique=False, schema='safety')
    op.create_index(op.f('idx_hazard_reports_department'), 'hazard_reports', ['department'], unique=False, schema='safety')
    op.create_index(op.f('idx_hazard_reports_check_id'), 'hazard_reports', ['check_id'], unique=False, schema='safety')
    op.alter_column('hazard_reports', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'check_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联检查ID',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"),
               schema='safety')
    op.alter_column('hazard_reports', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='验证时间',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'verified_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='验证人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'verified_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='验证人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'rectification_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='整改进度',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='safety')
    op.alter_column('hazard_reports', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='整改期限',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'control_measures',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='管控措施',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='责任部门',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='发现时间',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'discovered_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='发现人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'discovered_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='发现人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='地点/部位',
               existing_nullable=True,
               schema='safety')
    op.alter_column('hazard_reports', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='隐患描述',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_level',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='隐患等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='隐患类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('hazard_reports', 'hazard_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='隐患编号',
               existing_nullable=False,
               schema='safety')
    op.create_index(op.f('idx_accidents_status'), 'accidents', ['status'], unique=False, schema='safety')
    op.create_index(op.f('idx_accidents_happened_at'), 'accidents', ['happened_at'], unique=False, schema='safety')
    op.create_index(op.f('idx_accidents_accident_type'), 'accidents', ['accident_type'], unique=False, schema='safety')
    op.create_index(op.f('idx_accidents_accident_no'), 'accidents', ['accident_no'], unique=False, schema='safety')
    op.alter_column('accidents', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'investigator_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='调查人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'investigator',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='调查人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'reported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='报告时间',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'reported_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='报告人姓名',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'reported_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='报告人',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'reported'::character varying"),
               schema='safety')
    op.alter_column('accidents', 'corrective_actions',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='纠正预防措施',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'handling_measures',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='处理措施',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'root_cause',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='根本原因',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'direct_cause',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='直接原因',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'property_damage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='财产损失(元)',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'casualties',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='伤亡情况',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='事故描述',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='发生地点',
               existing_nullable=True,
               schema='safety')
    op.alter_column('accidents', 'happened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='发生时间',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'accident_level',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='事故等级',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'accident_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='事故类型',
               existing_nullable=False,
               schema='safety')
    op.alter_column('accidents', 'accident_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='事故编号',
               existing_nullable=False,
               schema='safety')
    op.create_index(op.f('idx_production_records_operation_time'), 'production_records', ['operation_time'], unique=False, schema='production')
    op.create_index(op.f('idx_production_records_batch_id'), 'production_records', ['batch_id'], unique=False, schema='production')
    op.alter_column('production_records', 'remarks',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'result',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='操作结果',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'parameters',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='参数JSON',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'operation_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='操作类型',
               existing_nullable=False,
               schema='production')
    op.alter_column('production_records', 'operation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='操作时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='production')
    op.alter_column('production_records', 'operator_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='操作人姓名',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'operator',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='操作人',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'step_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='步骤名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'step_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤序号',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_records', 'record_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='记录编号',
               existing_nullable=False,
               schema='production')
    op.alter_column('production_records', 'batch_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='批次ID',
               existing_nullable=False,
               schema='production')
    op.create_index(op.f('idx_production_plans_status'), 'production_plans', ['status'], unique=False, schema='production')
    op.create_index(op.f('idx_production_plans_plan_month'), 'production_plans', ['plan_month'], unique=False, schema='production')
    op.alter_column('production_plans', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'completed_batches',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='已完成批次',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'total_batches',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='总批次',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='production')
    op.alter_column('production_plans', 'plan_month',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='计划月份YYYY-MM',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'plan_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='计划类型:月计划/周计划',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'plan_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='计划名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('production_plans', 'plan_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='计划编号',
               existing_nullable=False,
               schema='production')
    op.create_index(op.f('idx_process_steps_spec_id'), 'process_steps', ['spec_id'], unique=False, schema='production')
    op.alter_column('process_steps', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'sequence_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'duration_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='持续时间(分钟)',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'equipment_spec',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='设备规格',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'equipment_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='设备类型',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='步骤描述',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_steps', 'step_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='步骤名称',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_steps', 'step_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='步骤序号',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_steps', 'spec_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='规程ID',
               existing_nullable=False,
               schema='production')
    op.create_index(op.f('idx_process_specs_status'), 'process_specs', ['status'], unique=False, schema='production')
    op.create_index(op.f('idx_process_specs_product_code'), 'process_specs', ['product_code'], unique=False, schema='production')
    op.alter_column('process_specs', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'supersedes_version',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='替代版本',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='批准时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'approved_by_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='批准人姓名',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'approved_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='批准人',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'effective_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生效日期',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='production')
    op.alter_column('process_specs', 'version',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='版本号',
               existing_nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"),
               schema='production')
    op.alter_column('process_specs', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='产品名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'product_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产品编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_specs', 'spec_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='规程名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_specs', 'spec_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='规程编号',
               existing_nullable=False,
               schema='production')
    op.create_index(op.f('idx_process_parameters_step_id'), 'process_parameters', ['step_id'], unique=False, schema='production')
    op.alter_column('process_parameters', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'data_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='数据类型:numeric/text/boolean',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'is_critical',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否关键参数',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_parameters', 'target_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='目标值',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'max_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最大值',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'min_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='最小值',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='单位',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'param_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='参数编码',
               existing_nullable=True,
               schema='production')
    op.alter_column('process_parameters', 'param_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='参数名称',
               existing_nullable=False,
               schema='production')
    op.alter_column('process_parameters', 'step_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='步骤ID',
               existing_nullable=False,
               schema='production')
    op.create_index(op.f('idx_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False, schema='production')
    op.alter_column('plan_tasks', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='production')
    op.alter_column('plan_tasks', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='计划完成日期',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'assigned_to_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='负责人姓名',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'assigned_to',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='负责人',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'batch_qty',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='批次数量',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='产品名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('plan_tasks', 'product_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产品编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('plan_tasks', 'plan_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='计划ID',
               existing_nullable=False,
               schema='production')
    op.alter_column('material_balances', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='计算时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'deviation_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='偏差率(%)',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'is_balanced',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='是否平衡',
               existing_nullable=False,
               schema='production')
    op.alter_column('material_balances', 'min_balance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('95.0'),
               comment=None,
               existing_comment='最低平衡率(%)',
               existing_nullable=False,
               schema='production')
    op.alter_column('material_balances', 'balance_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='平衡率(%)',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'loss_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='损耗总量',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'output_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='产出总量',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'input_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='投入总量',
               existing_nullable=True,
               schema='production')
    op.alter_column('material_balances', 'batch_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='批次ID',
               existing_nullable=False,
               schema='production')
    op.drop_constraint(None, 'batches', schema='production', type_='foreignkey')
    op.create_index(op.f('idx_batches_status'), 'batches', ['status'], unique=False, schema='production')
    op.create_index(op.f('idx_batches_product_code'), 'batches', ['product_code'], unique=False, schema='production')
    op.create_index(op.f('idx_batches_batch_no'), 'batches', ['batch_no'], unique=False, schema='production')
    op.alter_column('batches', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='结束时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始时间',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'production_line',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='生产线',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'process_spec_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='工艺规程ID',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'actual_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='实际产出数量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'planned_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='计划数量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='状态',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"),
               schema='production')
    op.alter_column('batches', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='单位',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'specification',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='规格',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'product_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='产品名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('batches', 'product_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='产品编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('batches', 'batch_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='批次号',
               existing_nullable=False,
               schema='production')
    op.drop_column('batches', 'input_qty', schema='production')
    op.create_index(op.f('idx_batch_materials_batch_id'), 'batch_materials', ['batch_id'], unique=False, schema='production')
    op.alter_column('batch_materials', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'stage',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='工序阶段',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'lot_no',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='批号/批次',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'actual_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='实际用量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'planned_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='计划用量',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='单位',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'material_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='物料类型',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'material_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='物料名称',
               existing_nullable=True,
               schema='production')
    op.alter_column('batch_materials', 'material_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='物料编码',
               existing_nullable=False,
               schema='production')
    op.alter_column('batch_materials', 'batch_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='批次ID',
               existing_nullable=False,
               schema='production')
    op.drop_column('users', 'feishu_department_id', schema='identity')
    op.drop_constraint(None, 'maintenance_plans', schema='equipment', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_plans', schema='equipment', type_='foreignkey')
    op.alter_column('maintenance_plans', 'plan_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'预防性维护'::character varying"),
               existing_comment='计划类型：预防性维护/预测性维护',
               existing_nullable=False,
               schema='equipment')
    op.drop_column('maintenance_plans', 'updated_by', schema='equipment')
    op.drop_column('maintenance_plans', 'created_by', schema='equipment')
    op.drop_constraint(None, 'inspection_templates', schema='equipment', type_='foreignkey')
    op.drop_constraint(None, 'inspection_templates', schema='equipment', type_='foreignkey')
    op.drop_column('inspection_templates', 'updated_by', schema='equipment')
    op.drop_column('inspection_templates', 'created_by', schema='equipment')
    op.alter_column('inspection_records', 'remark',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='备注',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_records', 'actual_value',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='实际值',
               existing_nullable=True,
               schema='equipment')
    op.alter_column('inspection_records', 'result',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='结果：正常/异常/跳过',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_records', 'template_item_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='检查项ID',
               existing_nullable=False,
               schema='equipment')
    op.alter_column('inspection_records', 'work_order_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联巡检工单ID',
               existing_nullable=False,
               schema='equipment')
    op.drop_table('work_order_images', schema='equipment')
    op.drop_table('maintenance_config', schema='equipment')
    # ### end Alembic commands ###
