"""add responsible_person_id to work_orders and update order_type check constraint

Revision ID: a2eb9476d3c9
Revises: 44765a397e77
Create Date: 2026-06-10 18:03:20.342497
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2eb9476d3c9'
down_revision: Union[str, None] = '44765a397e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 更新 order_type check constraint，添加"异常处理"和"日常维护"
    op.drop_constraint('ck_work_orders_order_type', 'work_orders', schema='equipment', type_='check')
    op.create_check_constraint(
        'ck_work_orders_order_type',
        'work_orders',
        "order_type IN ('故障维修', '计划维护', '巡检', '校准', '异常处理', '日常维护')",
        schema='equipment',
    )
    op.add_column('work_orders', sa.Column('responsible_person_id', sa.Uuid(), nullable=True, comment='责任人ID'), schema='equipment')
    op.alter_column('work_orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               comment='工单类型：故障维修/计划维护/巡检/校准/异常处理/日常维护',
               existing_comment='工单类型：故障维修/校准',
               existing_nullable=False,
               schema='equipment')
    op.create_foreign_key(None, 'work_orders', 'users', ['responsible_person_id'], ['id'], source_schema='equipment', referent_schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', schema='equipment', type_='foreignkey')
    op.alter_column('work_orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               comment='工单类型：故障维修/校准',
               existing_comment='工单类型：故障维修/计划维护/巡检/校准/异常处理/日常维护',
               existing_nullable=False,
               schema='equipment')
    op.drop_column('work_orders', 'responsible_person_id', schema='equipment')
    # 恢复原始 order_type check constraint
    op.drop_constraint('ck_work_orders_order_type', 'work_orders', schema='equipment', type_='check')
    op.create_check_constraint(
        'ck_work_orders_order_type',
        'work_orders',
        "order_type IN ('故障维修', '计划维护', '巡检', '校准')",
        schema='equipment',
    )
    # ### end Alembic commands ###
