"""add equipment personnel tables

Revision ID: e2b2fab66547
Revises: 1b6263216455
Create Date: 2026-06-08 18:23:30.834091
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2b2fab66547'
down_revision: Union[str, None] = '1b6263216455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_personnel',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='逻辑引用 identity.users.id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='冗余，人员姓名'),
    sa.Column('employee_no', sa.String(length=64), nullable=True, comment='冗余，工号'),
    sa.Column('department', sa.String(length=200), nullable=True, comment='冗余，部门'),
    sa.Column('feishu_user_id', sa.String(length=128), nullable=True, comment='飞书 user_id（发消息通知用）'),
    sa.Column('feishu_open_id', sa.String(length=128), nullable=True, comment='飞书 open_id'),
    sa.Column('mobile', sa.String(length=32), nullable=True, comment='冗余，手机号'),
    sa.Column('extended_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性槽'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否在岗'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='equipment'
    )
    op.create_index('ix_equipment_personnel_feishu_user_id', 'equipment_personnel', ['feishu_user_id'], unique=False, schema='equipment')
    op.create_index('ix_equipment_personnel_name', 'equipment_personnel', ['name'], unique=False, schema='equipment')
    op.create_index('ix_equipment_personnel_user_id', 'equipment_personnel', ['user_id'], unique=False, schema='equipment')
    op.create_table('equipment_personnel_category',
    sa.Column('personnel_id', sa.UUID(), nullable=False, comment='逻辑引用 equipment_personnel.id'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='逻辑引用 equipment_role.id'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='逻辑引用 equipment_categories.id'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_id', 'role_id', 'category_id', name='uq_equipment_personnel_category'),
    schema='equipment'
    )
    op.create_table('equipment_personnel_role',
    sa.Column('personnel_id', sa.UUID(), nullable=False, comment='逻辑引用 equipment_personnel.id'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='逻辑引用 equipment_role.id'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_id', 'role_id', name='uq_equipment_personnel_role'),
    schema='equipment'
    )
    op.create_table('equipment_role',
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('scope', sa.String(length=50), server_default='global', nullable=False, comment='作用域'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_equipment_role_code'),
    schema='equipment'
    )
    op.create_index('ix_equipment_role_scope_deleted', 'equipment_role', ['scope', 'is_deleted'], unique=False, schema='equipment')
    op.alter_column('energy_alert_rules', 'monitor_metric',
               existing_type=sa.VARCHAR(length=20),
               comment='监控指标: instant/daily_total/monthly_total',
               existing_comment='监控指标',
               existing_nullable=False,
               schema='energy')
    op.alter_column('energy_alert_rules', 'notify_method',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='通知方式: email/sms/feishu',
               existing_comment='通知方式',
               existing_nullable=False,
               schema='energy')
    op.alter_column('energy_alert_rules', 'custom_time_start',
               existing_type=sa.VARCHAR(length=8),
               comment='自定义开始时间(HH:MM:SS)',
               existing_comment='自定义开始时间',
               existing_nullable=True,
               schema='energy')
    op.alter_column('energy_alert_rules', 'custom_time_end',
               existing_type=sa.VARCHAR(length=8),
               comment='自定义结束时间(HH:MM:SS)',
               existing_comment='自定义结束时间',
               existing_nullable=True,
               schema='energy')
    op.alter_column('energy_device_configs', 'energy_type',
               existing_type=sa.VARCHAR(length=20),
               comment='能源类型: electricity/water/gas',
               existing_comment='能源类型: electricity/steam/water',
               existing_nullable=False,
               schema='energy')
    op.alter_column('departments', 'path',
               existing_type=sa.TEXT(),
               comment="部门路径 JSON，如 [{'name':'公司','id':'xxx'},...]",
               existing_comment='部门路径 JSON，如 [{"name":"公司","id":"xxx"},...]',
               existing_nullable=True,
               schema='identity')
    op.add_column('special_operation_reports', sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False, comment='是否关键作业（AI自动判定+可手动修改）'), schema='safety')
    op.add_column('special_operation_reports', sa.Column('is_critical_reason', sa.Text(), nullable=True, comment='关键作业判定理由'), schema='safety')
    op.add_column('special_operation_reports', sa.Column('is_critical_updated_by', sa.String(length=100), nullable=True, comment='手动修改关键作业标记的操作人'), schema='safety')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_operation_reports', 'is_critical_updated_by', schema='safety')
    op.drop_column('special_operation_reports', 'is_critical_reason', schema='safety')
    op.drop_column('special_operation_reports', 'is_critical', schema='safety')
    op.alter_column('departments', 'path',
               existing_type=sa.TEXT(),
               comment='部门路径 JSON，如 [{"name":"公司","id":"xxx"},...]',
               existing_comment="部门路径 JSON，如 [{'name':'公司','id':'xxx'},...]",
               existing_nullable=True,
               schema='identity')
    op.alter_column('energy_device_configs', 'energy_type',
               existing_type=sa.VARCHAR(length=20),
               comment='能源类型: electricity/steam/water',
               existing_comment='能源类型: electricity/water/gas',
               existing_nullable=False,
               schema='energy')
    op.alter_column('energy_alert_rules', 'custom_time_end',
               existing_type=sa.VARCHAR(length=8),
               comment='自定义结束时间',
               existing_comment='自定义结束时间(HH:MM:SS)',
               existing_nullable=True,
               schema='energy')
    op.alter_column('energy_alert_rules', 'custom_time_start',
               existing_type=sa.VARCHAR(length=8),
               comment='自定义开始时间',
               existing_comment='自定义开始时间(HH:MM:SS)',
               existing_nullable=True,
               schema='energy')
    op.alter_column('energy_alert_rules', 'notify_method',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='通知方式',
               existing_comment='通知方式: email/sms/feishu',
               existing_nullable=False,
               schema='energy')
    op.alter_column('energy_alert_rules', 'monitor_metric',
               existing_type=sa.VARCHAR(length=20),
               comment='监控指标',
               existing_comment='监控指标: instant/daily_total/monthly_total',
               existing_nullable=False,
               schema='energy')
    op.drop_index('ix_equipment_role_scope_deleted', table_name='equipment_role', schema='equipment')
    op.drop_table('equipment_role', schema='equipment')
    op.drop_table('equipment_personnel_role', schema='equipment')
    op.drop_table('equipment_personnel_category', schema='equipment')
    op.drop_index('ix_equipment_personnel_user_id', table_name='equipment_personnel', schema='equipment')
    op.drop_index('ix_equipment_personnel_name', table_name='equipment_personnel', schema='equipment')
    op.drop_index('ix_equipment_personnel_feishu_user_id', table_name='equipment_personnel', schema='equipment')
    op.drop_table('equipment_personnel', schema='equipment')
    # ### end Alembic commands ###
