"""Safety API — aggregated router.

Auto-generated by split_api.py. All endpoints now live in api/ sub-files.
"""

from fastapi import APIRouter

from app.modules.safety.api.accidents import accidents_router
from app.modules.safety.api.checks import checks_router
from app.modules.safety.api.contractors import contractors_router
from app.modules.safety.api.daily_risk_reports import daily_risk_reports_router
from app.modules.safety.api.ehs_changes import ehs_changes_router
from app.modules.safety.api.enums import enums_router
from app.modules.safety.api.feishu import feishu_router
from app.modules.safety.api.files import files_router
from app.modules.safety.api.hazard_identifications import hazard_identifications_router
from app.modules.safety.api.hazards import hazards_router
from app.modules.safety.api.knowledge import knowledge_router
from app.modules.safety.api.oh_hazard_monitors import oh_hazard_monitors_router
from app.modules.safety.api.oh_health_exams import oh_health_exams_router
from app.modules.safety.api.regulations import regulations_router
from app.modules.safety.api.special_operation_reports import (
    special_operation_reports_router,
)
from app.modules.safety.api.special_ops_permits import special_ops_permits_router
from app.modules.safety.api.special_ops_personnel import special_ops_personnel_router
from app.modules.safety.api.trainings import trainings_router

router = APIRouter()

router.include_router(accidents_router)
router.include_router(checks_router)
router.include_router(contractors_router)
router.include_router(daily_risk_reports_router)
router.include_router(ehs_changes_router)
router.include_router(enums_router)
router.include_router(feishu_router)
router.include_router(files_router)
router.include_router(hazard_identifications_router)
router.include_router(hazards_router)
router.include_router(knowledge_router)
router.include_router(oh_hazard_monitors_router)
router.include_router(oh_health_exams_router)
router.include_router(regulations_router)
router.include_router(special_operation_reports_router)
router.include_router(special_ops_permits_router)
router.include_router(special_ops_personnel_router)
router.include_router(trainings_router)
