"""Safety API — aggregated router.

Auto-generated by split_api.py. All endpoints now live in api/ sub-files.
"""

from fastapi import APIRouter

from app.modules.safety.api.ai_audits import ai_audits_router
from app.modules.safety.api.bitable_config import bitable_config_router
from app.modules.safety.api.business_agent import business_agent_router
from app.modules.safety.api.central_alarm import central_alarm_router
from app.modules.safety.api.cert_warnings import cert_warnings_router
from app.modules.safety.api.chemical_inventory import chemical_inventory_router
from app.modules.safety.api.contractor_admission import contractor_admission_router
from app.modules.safety.api.contractors import contractors_router
from app.modules.safety.api.ehs_changes import ehs_changes_router
from app.modules.safety.api.emergency_drills import emergency_drills_router
from app.modules.safety.api.enums import enums_router
from app.modules.safety.api.feishu import feishu_router
from app.modules.safety.api.files import files_router
from app.modules.safety.api.fire_alarm import fire_alarm_router
from app.modules.safety.api.hazard_identifications import hazard_identifications_router
from app.modules.safety.api.hazards import hazards_router
from app.modules.safety.api.info_query import info_query_router
from app.modules.safety.api.key_risk_operation_reports import (
    key_risk_operation_reports_router,
)
from app.modules.safety.api.knowledge import knowledge_router
from app.modules.safety.api.msds import msds_router
from app.modules.safety.api.oh_exam_applications import oh_exam_applications_router
from app.modules.safety.api.oh_followups import oh_followups_router
from app.modules.safety.api.oh_hazard_factors import oh_hazard_factors_router
from app.modules.safety.api.oh_health_exams import oh_health_exams_router
from app.modules.safety.api.oh_persons import oh_persons_router
from app.modules.safety.api.oh_positions import oh_positions_router
from app.modules.safety.api.regulations import regulations_router
from app.modules.safety.api.scheduler_config import scheduler_config_router
from app.modules.safety.api.special_operation_daily_report import (
    special_operation_daily_report_router,
)
from app.modules.safety.api.special_operation_reports import (
    special_operation_reports_router,
)
from app.modules.safety.api.special_ops_permits import special_ops_permits_router
from app.modules.safety.api.special_ops_personnel import special_ops_personnel_router
from app.modules.safety.api.trainings import trainings_router
from app.modules.safety.api.urs import urs_router
from app.modules.safety.api.workticket_review import workticket_review_router
from app.modules.safety.knowledge.graph_api import graph_router

router = APIRouter()

router.include_router(ai_audits_router)
router.include_router(bitable_config_router)
router.include_router(cert_warnings_router)
router.include_router(chemical_inventory_router)
router.include_router(business_agent_router)
router.include_router(central_alarm_router)
router.include_router(contractors_router)
router.include_router(contractor_admission_router)
router.include_router(ehs_changes_router)
router.include_router(emergency_drills_router)
router.include_router(enums_router)
router.include_router(feishu_router)
router.include_router(files_router)
router.include_router(fire_alarm_router)
router.include_router(hazard_identifications_router)
router.include_router(hazards_router)
router.include_router(info_query_router)
router.include_router(key_risk_operation_reports_router)
router.include_router(knowledge_router)
router.include_router(graph_router)
router.include_router(msds_router)
router.include_router(oh_health_exams_router)
router.include_router(oh_persons_router)
router.include_router(oh_positions_router)
router.include_router(oh_hazard_factors_router)
router.include_router(oh_exam_applications_router)
router.include_router(oh_followups_router)
router.include_router(regulations_router)
router.include_router(scheduler_config_router)
router.include_router(special_operation_daily_report_router)
router.include_router(special_operation_reports_router)
router.include_router(special_ops_permits_router)
router.include_router(special_ops_personnel_router)
router.include_router(trainings_router)
router.include_router(urs_router)
router.include_router(workticket_review_router)
