"""Equipment module schemas."""

from app.modules.equipment.schemas.calibration import (
    CalibrationPlanCreate,
    CalibrationPlanResponse,
    CalibrationPlanStatus,
    CalibrationPlanUpdate,
    CalibrationRecordCreate,
    CalibrationRecordResponse,
    CalibrationResult,
    CalibrationType,
)
from app.modules.equipment.schemas.equipment import (
    EquipmentCategoryCreate,
    EquipmentCategoryResponse,
    EquipmentCategoryTree,
    EquipmentCategoryUpdate,
    EquipmentCreate,
    EquipmentImportance,
    EquipmentImportResponse,
    EquipmentResponse,
    EquipmentStatistics,
    EquipmentStatus,
    EquipmentUpdate,
    ImportRowError,
    LocationCreate,
    LocationResponse,
    LocationTree,
    LocationUpdate,
)
from app.modules.equipment.schemas.failure_code import (
    FailureCodeCreate,
    FailureCodeResponse,
    FailureCodeType,
    FailureCodeUpdate,
)
from app.modules.equipment.schemas.inspection import (
    CheckResult,
    EquipmentCheckResult,
    InspectionAIAnalyzeRequest,
    InspectionAIAnalyzeResponse,
    InspectionAIItemResult,
    InspectionOverallResult,
    InspectionScheduleCreate,
    InspectionScheduleResponse,
    InspectionScheduleUpdate,
    InspectionPhotoResponse,
    InspectionPlanType,
    InspectionRouteCreate,
    InspectionRouteDetailResponse,
    InspectionRouteEquipmentBatch,
    InspectionRouteEquipmentItem,
    InspectionRouteResponse,
    InspectionRouteUpdate,
    InspectionTaskClose,
    InspectionTaskCreate,
    InspectionTaskDetailResponse,
    InspectionTaskResponse,
    InspectionTaskStatus,
    InspectionTaskUpdate,
    RouteCheckSubmit,
    RouteEquipmentResponse,
)
from app.modules.equipment.schemas.inspection_template import (
    InspectionCompleteRequest,
    InspectionRecordItem,
    InspectionRecordResponse,
    InspectionTemplateCreate,
    InspectionTemplateItemCreate,
    InspectionTemplateItemResponse,
    InspectionTemplateItemUpdate,
    InspectionTemplateResponse,
    InspectionTemplateUpdate,
)
from app.modules.equipment.schemas.maintenance_config import (
    ClaimTimeoutConfig,
    ClaimTimeoutUpdateRequest,
)
from app.modules.equipment.schemas.maintenance_plan import (
    FrequencyUnit,
    MaintenancePlanCreate,
    MaintenancePlanResponse,
    MaintenancePlanStatus,
    MaintenancePlanType,
    MaintenancePlanUpdate,
)
from app.modules.equipment.schemas.personnel import (
    CandidateResponse,
    FeishuRefreshResult,
    PersonnelAddRequest,
    PersonnelAddResult,
    PersonnelCategoryAssign,
    PersonnelCategoryInfo,
    PersonnelCategoryItem,
    PersonnelListResponse,
    PersonnelResponse,
    PersonnelRoleAssign,
    PersonnelRoleInfo,
    PersonnelUpdate,
    RoleCreate,
    RoleResponse,
    RoleUpdate,
)
from app.modules.equipment.schemas.spare_part import (
    EquipmentSparePartCreate,
    EquipmentSparePartResponse,
    SparePartCreate,
    SparePartResponse,
    SparePartUpdate,
    StockAdjustRequest,
    StockInboundRequest,
    StockResponse,
    StockWarningResponse,
)
from app.modules.equipment.schemas.work_order import (
    MaterialConsumeItem,
    MaterialConsumeRequest,
    MaterialConsumeResponse,
    VerificationResult,
    WorkOrderAssign,
    WorkOrderComplete,
    WorkOrderCreate,
    WorkOrderPriority,
    WorkOrderResponse,
    WorkOrderStatistics,
    WorkOrderStatus,
    WorkOrderType,
    WorkOrderUpdate,
    WorkOrderVerify,
)
from app.modules.equipment.schemas.work_order_image import (
    WorkOrderImageResponse,
)

__all__ = [
    # equipment
    "EquipmentStatus",
    "EquipmentCategoryCreate",
    "EquipmentCategoryUpdate",
    "EquipmentCategoryResponse",
    "EquipmentCategoryTree",
    "LocationCreate",
    "LocationUpdate",
    "LocationResponse",
    "LocationTree",
    "EquipmentCreate",
    "EquipmentUpdate",
    "EquipmentResponse",
    "EquipmentStatistics",
    "EquipmentImportance",
    "EquipmentImportResponse",
    "ImportRowError",
    # failure code
    "FailureCodeType",
    "FailureCodeCreate",
    "FailureCodeUpdate",
    "FailureCodeResponse",
    # inspection AI
    "InspectionAIAnalyzeRequest",
    "InspectionAIAnalyzeResponse",
    "InspectionAIItemResult",
    # inspection template
    "InspectionCompleteRequest",
    "InspectionRecordItem",
    "InspectionRecordResponse",
    "InspectionTemplateCreate",
    "InspectionTemplateUpdate",
    "InspectionTemplateResponse",
    "InspectionTemplateItemCreate",
    "InspectionTemplateItemUpdate",
    "InspectionTemplateItemResponse",
    # maintenance plan
    "MaintenancePlanType",
    "FrequencyUnit",
    "MaintenancePlanStatus",
    "MaintenancePlanCreate",
    "MaintenancePlanUpdate",
    "MaintenancePlanResponse",
    # work order
    "WorkOrderType",
    "WorkOrderPriority",
    "WorkOrderStatus",
    "VerificationResult",
    "WorkOrderCreate",
    "WorkOrderUpdate",
    "WorkOrderAssign",
    "WorkOrderComplete",
    "WorkOrderVerify",
    "WorkOrderResponse",
    "WorkOrderStatistics",
    # calibration
    "CalibrationType",
    "CalibrationResult",
    "CalibrationPlanStatus",
    "CalibrationPlanCreate",
    "CalibrationPlanUpdate",
    "CalibrationPlanResponse",
    "CalibrationRecordCreate",
    "CalibrationRecordResponse",
    # material consume
    "MaterialConsumeItem",
    "MaterialConsumeRequest",
    "MaterialConsumeResponse",
    # spare part
    "SparePartCreate",
    "SparePartUpdate",
    "SparePartResponse",
    "StockResponse",
    "StockInboundRequest",
    "StockAdjustRequest",
    "StockWarningResponse",
    "EquipmentSparePartCreate",
    "EquipmentSparePartResponse",
    # maintenance config
    "ClaimTimeoutConfig",
    "ClaimTimeoutUpdateRequest",
    # inspection
    "RouteCheckSubmit",
    # work order image
    "WorkOrderImageResponse",
    # personnel
    "CandidateResponse",
    "FeishuRefreshResult",
    "PersonnelAddRequest",
    "PersonnelAddResult",
    "PersonnelCategoryAssign",
    "PersonnelCategoryInfo",
    "PersonnelCategoryItem",
    "PersonnelListResponse",
    "PersonnelResponse",
    "PersonnelRoleAssign",
    "PersonnelRoleInfo",
    "PersonnelUpdate",
    "RoleCreate",
    "RoleResponse",
    "RoleUpdate",
]
